### ISSUE TITLE
The mail certificates on twistedmatrix.com can't be verified

### ISSUE THREAD

**Issue by exarkun** [twisted-infra/braid#154]
There are a few issues:

```
$ openssl s_client -verify 1 -connect mail.twistedmatrix.com:465 2>&1 | grep -E "CN|Verify return code"                                                        
depth=0 C = US, ST = Massachusetts, L = Boston, O = Twisted Matrix Labs, CN = cube.twistedmatrix.com, emailAddress = root@twistedmatrix.com
depth=0 C = US, ST = Massachusetts, L = Boston, O = Twisted Matrix Labs, CN = cube.twistedmatrix.com, emailAddress = root@twistedmatrix.com
depth=0 C = US, ST = Massachusetts, L = Boston, O = Twisted Matrix Labs, CN = cube.twistedmatrix.com, emailAddress = root@twistedmatrix.com
 0 s:/C=US/ST=Massachusetts/L=Boston/O=Twisted Matrix Labs/CN=cube.twistedmatrix.com/emailAddress=root@twistedmatrix.com
   i:/C=US/ST=Massachusetts/L=Boston/O=Twisted Matrix Labs/CN=cube.twistedmatrix.com/emailAddress=root@twistedmatrix.com
subject=/C=US/ST=Massachusetts/L=Boston/O=Twisted Matrix Labs/CN=cube.twistedmatrix.com/emailAddress=root@twistedmatrix.com
issuer=/C=US/ST=Massachusetts/L=Boston/O=Twisted Matrix Labs/CN=cube.twistedmatrix.com/emailAddress=root@twistedmatrix.com
    Verify return code: 10 (certificate has expired)
^C
$ openssl s_client -verify 1 -connect mail.twistedmatrix.com:993 2>&1 | grep -E "CN|Verify return code"                                                        
depth=0 O = Dovecot mail server, OU = dornkirk.twistedmatrix.com, CN = dornkirk.twistedmatrix.com, emailAddress = root@twistedmatrix.com
depth=0 O = Dovecot mail server, OU = dornkirk.twistedmatrix.com, CN = dornkirk.twistedmatrix.com, emailAddress = root@twistedmatrix.com
 0 s:/O=Dovecot mail server/OU=dornkirk.twistedmatrix.com/CN=dornkirk.twistedmatrix.com/emailAddress=root@twistedmatrix.com
   i:/O=Dovecot mail server/OU=dornkirk.twistedmatrix.com/CN=dornkirk.twistedmatrix.com/emailAddress=root@twistedmatrix.com
subject=/O=Dovecot mail server/OU=dornkirk.twistedmatrix.com/CN=dornkirk.twistedmatrix.com/emailAddress=root@twistedmatrix.com
issuer=/O=Dovecot mail server/OU=dornkirk.twistedmatrix.com/CN=dornkirk.twistedmatrix.com/emailAddress=root@twistedmatrix.com
    Verify return code: 18 (self signed certificate)
^C
$ openssl s_client -verify 1 -connect mail.twistedmatrix.com:995 2>&1 | grep -E "CN|Verify return code"                                                        
depth=0 O = Dovecot mail server, OU = dornkirk.twistedmatrix.com, CN = dornkirk.twistedmatrix.com, emailAddress = root@twistedmatrix.com
depth=0 O = Dovecot mail server, OU = dornkirk.twistedmatrix.com, CN = dornkirk.twistedmatrix.com, emailAddress = root@twistedmatrix.com
 0 s:/O=Dovecot mail server/OU=dornkirk.twistedmatrix.com/CN=dornkirk.twistedmatrix.com/emailAddress=root@twistedmatrix.com
   i:/O=Dovecot mail server/OU=dornkirk.twistedmatrix.com/CN=dornkirk.twistedmatrix.com/emailAddress=root@twistedmatrix.com
subject=/O=Dovecot mail server/OU=dornkirk.twistedmatrix.com/CN=dornkirk.twistedmatrix.com/emailAddress=root@twistedmatrix.com
issuer=/O=Dovecot mail server/OU=dornkirk.twistedmatrix.com/CN=dornkirk.twistedmatrix.com/emailAddress=root@twistedmatrix.com
    Verify return code: 18 (self signed certificate)
^C
```

It would be great if these certificates were current and for the correct hostname.

**Comment by glyph** [comment]
so we need a cert for `mail.twistedmatrix.com`?

**Comment by hawkowl** [comment]
I did a Let's Encrypt limited beta request, lets see if that happens.

**Comment by hawkowl** [comment]
LE responded and I've been whitelisted for:

mail.twistedmatrix.com
code.twistedmatrix.com
twistedmatrix.com
www.twistedmatrix.com

Think we should set this up, @glyph? It'll add a bit more to our process for right now, because Let's Encrypt certs are only valid for 90 days, so eventually there is going to be an automated server-side renewer. But then we have a way off StartSSL/etc.

**Comment by glyph** [comment]
Yes, let's set it up.  And can we please set up automatic server-side renewals immediately, rather than making it manual and then waiting?  The whole point about 90 day lifetimes is that they *assume* automation.  We can have an email that someone needs to reply to every 90 days or so, if necessary, but as I understand it they shouldn't have to *initiate* the renewal.

**Comment by hawkowl** [comment]
Let's Encrypt plan to have it for GA (early Dec) but they say it's "not done yet". I'm happy to do the manual renewal until this becomes a reality.

**Comment by exarkun** [comment]
Hi.  Any news on this?

**Comment by hawkowl** [comment]
No, sorry, burnout has been happening :(

@glyph is this on the same server as Trac?

**Comment by glyph** [comment]
Yes.

**Comment by exarkun** [comment]
Hi.  Sorry if this is contributing to burnout.  For now, I've just configured a .forward file.

**Comment by glyph** [comment]
Since their public beta, I've re-provisioned my personal server certificates using Let's Encrypt; I've built a docker container that I can share which uses `simp_le` to set up automatic renewals, so once we have a host with a new enough OS to run Docker we can just run that.

Thanks for switching to a .forward file, exarkun; sorry about the delay on this.  However, the issue definitely remains because 465 and 25/STARTTLS still ought to verify properly; one day, eventually, TLS will be required for SMTP and it would be nice if we were front-running that by a decade or so.

**Comment by glyph** [comment]
Oh hey we can actually close a braid ticket, this was fixed when we moved to mailgun.
