### ISSUE TITLE
Migrate contributors history to GitHub accounts

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#170]
Investigate ``.mailmap`` and similar to alter/amend history to update existing contributor metadata to be their current GitHub email

**Comment by rodrigc** [comment]
@hawkowl was this done?

**Comment by hawkowl** [comment]
Nope, we've not done any Git stuff (just making logins to Trac use GitHub). Also I think @glyph  has mentioned that it's effectively too hard, and we will just have to have bad history, rather than waste tens of hours on improving it slightly.

**Comment by rodrigc** [comment]
@glyph can you confirm this?

**Comment by glyph** [comment]
Yup.

**Comment by glyph** [comment]
There were two issues I'm aware of that have been raised with the history as it stands:

1. contributor metadata isn't accurate with respect to what the contributors' current email addresses are
2. the repo is too big for some reason (???)

With respect to the first, well, email addresses change, and there's nothing *inaccurate* about the current git history.  If you want your avatar icon to show up on GitHub, there's a trick to that (which various core contributors have done, as you can see on https://github.com/twisted/twisted/graphs/contributors).  If other people want to do that it would be great, but we're not _losing_ any information by using the SVN compatibility identifiers; in fact, it's less ambiguous, because it's clear that the commit was made under SVN.

With respect to the second, that never really sounded accurate to me.  I mean:

```console
$ du -sh django/
182M	django/
$ du -sh Twisted/
 68M	Twisted/
```

Our repo is large, but it seems like a reasonable size, given the length of its history.

So, I'm comfortable letting the existing history stand.  If anyone else has any reasons why they feel that it's important to change the information in historical commits I'm certainly willing to hear it, but every day that goes by where we don't use git, we're missing out on new, good metadata (including merge metadata!) so blocking on this seems bad.

**Comment by rodrigc** [comment]
Sounds good to me.  I agree with you.
Thanks for the clarification.

**Comment by hawkowl** [comment]
I agree. Lots of pain, little gain, and the size is, in context, probably reasonable.
