### ISSUE TITLE
Upgrade cryptography on osx10.10-py27

### ISSUE THREAD

**Issue by mithrandi** [twisted-infra/braid#182]
https://twistedmatrix.com/trac/ticket/7413 will require at least cryptography 1.0, but the OS X builder has an older version; is it possible to upgrade this?

**Comment by hawkowl** [comment]
cc @reaperhulk as it was to do with OS X wheels needing a too-new CPU arch for our 10.6-era mac mini

**Comment by reaperhulk** [comment]
The current wheels are compiled against bottled homebre was OpenSSL. This should mean their optimization target is march=core2duo and you shouldn't have an issue. If you do let me know though!

You may want to use 1.1.2 while we still work to sort out the interaction between static linking and the new cffi static callbacks. They're causing segfaults on shutdown for users in some situations (and the Windows shutdown but you reported is probably related @hawkowl )

**Comment by mithrandi** [comment]
I think I'm going to make #7413 work with cryptography 0.9.3 because it's not too much work, so this will no longer be necessary for that purpose.

**Comment by hawkowl** [comment]
@reaperhulk said that it the issue that made us pin was fixed, so we could update. If you're in a PRing mood (I'm currently away from real PC) the pinning is in services/buildbot/master/master.cfg and is special cased for just the 10.10 builder. I think a few others may have pinnings too, I will double check later. 
On 2 Feb 2016 12:11, Tristan Seligmann <notifications@github.com> wrote:I think I'm going to make #7413 work with cryptography 0.9.3 because it's not too much work, so this will no longer be necessary for that purpose.

**Comment by mithrandi** [comment]
Turns out this is still necessary, because the pin was to 0.9 which crashes in the DSA signature code (fixed in 0.9.1).

**Comment by hawkowl** [comment]
Huh. What's the pip-ism to "highest of 0.9.x" then?
On 2 Feb 2016 13:07, Tristan Seligmann <notifications@github.com> wrote:Turns out this is still necessary, because the pin was to 0.9 which crashes in the DSA signature code (fixed in 0.9.1).

**Comment by mithrandi** [comment]
"<1.0" I believe (at least that's what I went with).
