### ISSUE TITLE
Migrate commit mailer to Git hook

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#92]
**all** svn commits ( together with their diff) are notified over email at  
http://blog.gmane.org/gmane.comp.python.twisted.commits

This is done using a SVN hook

Since we are moving away from SVN we should update the hook.

---

My plan is to implement it using the GitHub hooks as we already mirror the code to GitHub and it should require minimal effort.

I would argue that we email only commits in trunk.

**Comment by adiroiban** [comment]
Since it is not that easy to run a staging mailman configured for Twisted and allow the staging to interact with external services, maybe we can create a staging/testing list inside the production mailman deployment.

We can then use that list to test the new git hooks without polluting the production twisted.commits list with test messages.

What do you think?

**Comment by rodrigc** [comment]
This needs to be set up:
https://github.com/twisted/twisted/settings/hooks/new?service=email

The twisted-commits@twistedmatrix.com mailing list hasn't been updated since May 10, 2016.

If no one cares about this, I would recommend just forgetting about it and closing this issue.  For people who are interested, there are other ways to monitor activity in a GitHub repo.
One less thing to worry about.  Email is a pain.

**Comment by adiroiban** [comment]
Ok. I will close this as wont-fix.

Thanks!
